@AddMember_HostAddress = http://localhost:8080

### Request for kids
POST {{AddMember_HostAddress}}/addmember?name=Oscar&lastname=Espinoza&birthyear=2020
Content-Type: application/json
Accept: application/json

### Request for adutls
POST {{AddMember_HostAddress}}/addmember?name=Docker&lastname=Ballena&birthyear=2000
Content-Type: application/json
Accept: application/json